py27:
  image: python:2.7
  script:
    - pip install tox
    - tox -e py27

py34:
  image: python:3.4
  script:
    - pip install tox
    - tox -e py34

py35:
  image: python:3.4
  script:
    - pip install tox
    - tox -e py35

py36:
  image: python:3.6
  script:
    - pip install tox
    - tox -e py36

py37:
  image: python:3.7
  script:
    - pip install tox
    - tox -e py37

pypy:
  image: python:pypy
  script:
    - pip install tox
    - tox -e pypy
